---
title: "Python analysis lab"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

```{r, echo = FALSE}
library(reticulate)
use_python("/anaconda3/bin/python")
```

* Load in the dataset, calling it `drinks_content`, and then briefly explore it, printing out: first 5 rows, last 5 rows, and then all of the data. Find out the dimensions of the data (number of rows and columns) and the column names.

* We're going to be looking at the number of `Calories` in each drink.
Calculate some quick summary statistics to check the mean, the variance, and the normality of this variable (i.e. plot a histogram).

* Check if you have any outliers in the `Calories` variable by creating a boxplot. (There is no need to change or remove any outliers you find)

* Select the variables `Beverage_category`, `Beverage`, `Beverage prep` and `Calories` from the `drinks_content` data frame, and assign the selected columns to a new data frame called `drinks`. Check if there are any `NaN` values anywhere in the data, and drop any rows containing them.

* Filter the data so we only take "Classic Espresso Drinks", and save this in a new data frame called `espresso_drinks`.

* Group your `espresso_drinks` data frame by the type of beverage prep, and then find out the mean calories for each drink group.

* Get the same grouped mean `Calories` values as above, but this time sorted in descending order.
