---
title: '`dplyr` Lab'
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=TRUE, fig.align = 'center')
library(tidyverse)
```

# dplyr lab

**Duration: 1 hour**

<br>

You now have an opportunity to practice the skills you've learnt today in a mini lab task. 

For this you will be using data which contains income generated by US states from year 2002 to 2015. Note : This data do not contain actual income figures of the states. This can be found in `state_income_data.csv`

This dataset contains 51 observations (rows) and 16 variables (columns). 

## Task

Answer the following questions: 

1. Load in the data.  
2. Select the variables "Index", columns from "State" to "Y2008".  
3. Rename the Index column to `first_letter`. *Hint: look up the `rename()` function*    
4. Group the data by what `first_letter` it has.    
5. Filter rows and retain only states which start with an C. 

<br>

From now on, work with your data tibble from above, which only has data for states that start with the letter C. <br>

6. Calculate the change in income for each state between 2005 and 2006. Save it in a new column called `income_change`.   
7. Find which state's income is greater than 1.9 million in year 2007.  
8. Arrange the data so that the state with the highest income in year 2007 is shown first.  
9. Calculate the mean and median for year 2008 for all three states.  
10. Write a pipe which groups the states by their first letter, chooses the year 2008, ranks the income from highest to lowest, and then finally filters all those states which have a ranking of 1.  (i.e. get the top income states for each letter) 

<br>
