---
title: "Python basics lab"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

```{r, echo = FALSE}
library(reticulate)
use_python("/anaconda3/bin/python")

knitr::opts_chunk$set(echo = FALSE, eval = FALSE)
```

The questions in this lab work up to be quite challenging. They are designed to test your new Python skills alongside your programming and puzzle solving skills! You may need to look up new syntax for Python that we've not yet learned. Don't be afraid to play and experiment!

Note, you solved some of these puzzles in week 1. You might want to look at your R solution.

# Who knows where the time goes?

Given a list of the years in which people were born, write a **list comprehension** to determine their age based on the current year. Ignore dates and months when calculating this.

`years_of_birth = [1990, 1991, 1990, 1990, 1992, 1991, 1976, 1984, 1940]`

# Back to front

Write a function `is_palindrome(input_string)` to determine whether an input string is a **palindrome** (i.e. reads the same backwards as forwards, e.g. 'madam'). The function should return `True` if the string is a palindrome and `False` otherwise. As an extension, amend your code so that it strips out spaces from the string. 

[**Hint** - to do this efficiently, research methods to reverse a string in Python]

# Multiples of 3 or 5

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

From Project Euler (Problem 1)

# No need to repeat yourself...

Write a function `remove_duplicates(input_list)` that takes in an input list of words and removes any duplicates it finds, returning the list without duplicates. For example with input:

`input_list = ["I", "am", "counting", "my", "calories", "yet", "I", "really", "want", "dessert", "I", "am", "still", "hungry"]`<br>

the function should output: 

`["I", "am", "counting", "my", "calories", "yet", "really", "want", "dessert", "still", "hungry"]`

[**Hint** research the `in` and `not` keywords in Python].


# List overlap

Write a function `list_overlap(list_1, list_2)` that returns the **overlap** between two input lists `list_1` and `list_2` of numbers (i.e. the elements present in both lists).  The input lists need not be the same size. For example, for the following inputs:

`list_1 = [1, 4, 5, 6, 6, 5, 10, 11, 12]`<br>
`list_2 = [3, 2, 6, 10]`

the function should output `[6, 10]` (or `[10, 6]`; order isn't important). 

# Even Fibonacci numbers

Each new term in a **Fibonacci sequence** is generated by adding the previous two terms. So starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in this Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

[**Hint** - research `while` loops]

From Project Euler (Problem 2)

# List to dictionary

Write a function that accepts a list of strings and returns a dictionary where the keys are the words from the list and the values are the number of times that word appears in the list.

# Correct the code

You are repeatedly sent a message, but there are errors in the message each time it is sent. Write code to determine which character occurs most frequently at each position. For example, suppose you had recorded the following messages:

eedadn
drvtee
eandsr
raavrd
atevrs
tsrnev
sdttsa
rasrtv
nssdts
ntnada
svetve
tesnvt
vntsnd
vrdear
dvrsen
enarar

The most common character in the first column is 'e'; in the second, 'a'; in the third, 's'; and so on. Combining these characters returns the error-corrected message 'easter'.

Open the file `puzzle3input.txt` and find the error corrected message.

From Advent of Code (2016, day 6)

# More?!

If you finish these questions and you want more practice, have a look at:

* https://projecteuler.net/about
* https://adventofcode.com/
